apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: vm-lb-pool
spec:
  blocks:
  - cidr: "192.168.0.32/27"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vm-lb-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
  - eth0
  - eth1
  - eth2
  - enp1s0
  - eno1
  - eno2
