apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sno-ztp-placement
  #namespace: open-cluster-management-policies
  namespace: openshift-gitops  
spec:
  clusterSets:
    - ocp-ztp-gitops
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - sno-ztp
