apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sno-ztp-placement
  namespace: open-cluster-management-policies
spec:
  clusterSets:
    - ocp-ztp-gitops
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - sno-ztp