apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: ztp-sno-placement
  #namespace: open-cluster-management-policies
  namespace: ztp-sno
spec:
  #clusterSets:
    #- ocp-ztp-gitops
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - ztp-sno
