apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: compliance-operator
spec:
  operatorGroup:
    name: default
  complianceType: musthave
  remediationAction: enforce
  severity: critical
  subscription:
    channel: 'stable'
    name: compliance-operator
    namespace: openshift-compliance
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  upgradeApproval: Automatic
  versions: null



