apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ubuntu-vw
  namespace: virtualmachines
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ubuntu-vw",
      "type": "bridge",
      "bridge": "br0",
      "promiscMode": true,
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.0.0/24",
        "range_start": "192.168.0.130",
        "range_end": "192.168.0.130",
        "gateway": "192.168.0.1",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ubuntu-vw-test
  namespace: virtualmachines
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ubuntu-vw-test",
      "type": "bridge",
      "bridge": "br0",
      "promiscMode": true,
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.0.0/24",
        "range_start": "192.168.0.131",
        "range_end": "192.168.0.131",
        "gateway": "192.168.0.1",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
