operator:
  replicas: 1
  image:
    tag: v1.17.3
kubeProxyReplacement: true
k8sServiceHost: "localhost"
k8sServicePort: "6443"
ipam:
  mode: kubernetes
cni:
  exclusive: false
l2announcements:
  enabled: true
externalIPs:
  enabled: true
socketLB:
  hostNamespaceOnly: true
ingressController:
  enabled: true
gatewayAPI:
  enabled: false
hubble:
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
    - http
    dashboards:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
  ui:
    enabled: true
