apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    operator:
      replicas: 2
      image:
        tag: v1.17.3
        #tag: v1.16.6
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    ipam:
      mode: kubernetes
    cni:
      exclusive: false
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    socketLB:
      hostNamespaceOnly: true
    ingressController:
      enabled: true
    gatewayAPI:
      enabled: false
    hubble:
      enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - icmp
        - http
        dashboards:
          enabled: true
      relay:
        enabled: true
        prometheus:
          enabled: true
