# Disk Clean POD using wipefs
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wipefs
  name: wipefs
  namespace: kube-system
spec:
  nodeName: lenevo-tc-w02
  #nodeName: lenevo-ts-w03
  containers:
  - image: docker.io/library/alpine:latest
    command:
    - /bin/sh
    args:
    - -c
    - apk update && apk add util-linux-misc coreutils && sleep 30 && wipefs -a /dev/nvme0n1
    securityContext:
      privileged: true
      seccompProfile:
        type: Unconfined
    imagePullPolicy: Always
    name: wipefs
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirstWithHostNet
  hostIPC: true
  hostPID: true
  hostNetwork: true
  restartPolicy: Always
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 300
