apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: cert-manager-operator
  namespace: open-cluster-management-policies
spec:
  complianceType: musthave
  remediationAction: enforce
  severity: critical
  subscription:
    channel: stable-v1
    name: openshift-cert-manager-operator
    namespace: cert-manager-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  upgradeApproval: Automatic
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudccafe-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: cloudccafe-ca
  secretName: cloudccafe-ca
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudccafe-ca-cluster-issuer
spec:
  ca:
    secretName: cloudccafe-ca
