{
 "title": "KubeVirt VM",
 "description": "KubeVirt VM Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubevirt_vm_info,exported_namespace)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(kubevirt_vm_info{exported_namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(kubevirt_vmi_vcpu_seconds_total{exported_namespace=\"$namespace\", name=\"$vm\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{exported_namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Storage IO Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_storage_read_traffic_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"})",
     "legendFormat": "-Read"
    },
    {
     "expr": "sum(kubevirt_vmi_storage_write_traffic_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"})",
     "legendFormat": "-Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_traffic_bytes_total{exported_namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  }
 ]
}