apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    release: kube-prometheus-stack
  name: ocp-console-custom-rule
spec:
    groups: 
    - name: ForOpenshiftConsole
      rules:
      - expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)
        record: instance:node_cpu:rate:sum
      - expr: sum(rate(container_cpu_usage_seconds_total{job="kubelet",container!="",container!="POD"}[2m])) by (namespace,pod)
        record: pod:container_cpu_usage:sum
      - expr: sum(container_network_receive_bytes_total{}) by(instance,namespace,pod,interface)
        record: instance:node_network_receive_bytes:rate:sum
      - expr: sum(container_network_transmit_bytes_total{}) by(instance,namespace,pod,interface)
        record: instance:node_network_transmit_bytes:rate:sum
      - expr: sum(kube_pod_container_resource_requests{container!=""}) by (node,namespace,pod,resource)
        record: kube_pod_resource_request
      - expr: sum(kube_pod_container_resource_limits{container!=""}) by (node,namespace,pod,resource)
        record: kube_pod_resource_limit
      - expr: sum(container_network_receive_bytes_total{}) by(namespace,pod,interface) * 0
        record: pod_network_name_info
      - expr: sum(container_fs_usage_bytes{}) by (namespace, pod)
        record: pod:container_fs_usage_bytes:sum  
