prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true
      relabelings:
       - sourceLabels: [__meta_kubernetes_pod_node_name]
         separator: ;
         regex: ^(.*)$
         targetLabel: instance
         replacement: $1
         action: replace
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
grafana:
  service:
    type: NodePort
alertmanager:
  service:
    type: NodePort
