apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: cGthcjokMnkkMDUkbFhRYXFCYS5sTE5MNDcxWGFGUEgvLk9mcVBybUV6dDVIb2NGeGxNOTdQNVNvLnFBMUpENWEKZGthcjokMnkkMDUkMVBtVTBIclpaaWVmaHdsenEwWEY3LlB1ZHRNUi4vNVV5OGtkdmtKd005S1F2Wm8zcm1qdmkK
