apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: sno-ztp
  namespace: sno-ztp
spec:
  clusterName: sno-ztp
  clusterImageSetNameRef: img4.20.11-x86-64-appsub  
  #clusterImageSetNameRef: img4.20.11-x86-64-appsub-ibi  
  baseDomain: pkar.tech
  cpuArchitecture: x86_64
  holdInstallation: false
  cpuPartitioningMode: None
  networkType: OVNKubernetes
  additionalNTPSources:
    - 192.168.0.159     
  extraLabels:
    ManagedCluster:
      mirrorRegistry: "mirror-registry.pkar.tech"
      timezone: "Asia-Kolkata"
      siteName: "store"
      common: "true"      
  extraManifestsRefs:
    - name: extra-manifests-cm 
  machineNetwork:
    - cidr: 192.168.0.0/24
  pullSecretRef:
    name: pull-secret
  templateRefs:
    - name: ibi-cluster-templates-v1    
      namespace: open-cluster-management
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWoz7bEt/HTXoRCJFCP310RlzDc6rtlguDoBqCMz+Em4DiY7F6b/+DUwdzGm6KHoHLsPxCV5RdtJ0D++SoFYZHy1J3rl3ASDKtiwWb4ifTcdUZxKHGU48N5j0qYtGB0nAK/BEJn3MI3BTqnuWWcutuDo6xH2aJ7HBUCpqaAaxXsrmp+AQjwpdYIyiKyMUexgByo1MPwU806oxJPiZwgIks6TR+Y0hE/zPfkfTHFTvMpOLu5YfuzgksTJhNxjNxPa4CNZzzRRqDWflWxVSI93iz5Atw/x5Q8sjxzCONfKIjPiRkky6sP2hpwB0cVr/p+U3n6UAYC5lmkqvdr/eh0EY2ZaQ4QsBhtxgTHrWW2l1xFDxVK8FxNfBZMyvSG8K8jingo3hE2udIIG43MpX4HM9Kg75SQTuDIZ4HxHQiSlYrcaNWVOckcZHYrs1AAMLUKtx5InhYa6YpC98WT1/MmP+45vA00UbU8Eh36CeorcC1MpGXmOnj00NYsVZoronPoic= root@lenevo-tci57
  nodes:
    - role: master
      hostName: sno-ztp
      ironicInspect: ''
      bootMACAddress: '52:54:00:42:a4:10'
      bootMode: UEFI
      automatedCleaningMode: disabled
      cpuArchitecture: x86_64
      templateRefs:
        - name: ibi-node-templates-v1        
          namespace: open-cluster-management
      bmcAddress: 'redfish-virtualmedia+http://192.168.0.161:8000/redfish/v1/Systems/d54f3990-12c9-4749-8b89-a1242e6af101'
      bmcCredentialsName:
        name: bmc-secret
      nodeNetwork:
        interfaces:
          - macAddress: '52:54:00:42:a4:10'
            name: enp1s0
        config:
          interfaces:
            - name: enp1s0
              type: ethernet
              state: up
              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 192.168.0.110
                    prefix-length: 24
              ipv6:
                enabled: false
          dns-resolver:
            config:
              search:
                - pkar.tech
              server:
                - 192.168.0.135
                - 192.168.0.159
                - 192.168.0.110
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.0.1
                next-hop-interface: enp1s0
