apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config
  namespace: sno-ztp
data:
  registries.conf: |
    unqualified-search-registries = ["registry.redhat.io", "registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release-images"

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp"

  policy.json: |
    {
        "default": [
            {
                "type": "insecureAcceptAnything"
            }
        ],
        "transports": {
            "docker": {
                "registry.access.redhat.com": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ],
                "registry.redhat.io": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ]
            },
            "docker-daemon": {
                "": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ]
            }
        }
    }

  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDpzCCAo+gAwIBAgIUe3Bt/ucT/qq4xmcmwpS3gN81qscwDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjEzMTQ0MzQ4WhcNMjcwMjA0
    MTQ0MzQ4WjAaMRgwFgYDVQQDDA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQCTWEmR1gPFwZ6nLW1xo6Yy0t0Ff8fgV7dF/hzU
    0bMjFRGHOmP8Lk7600nbAEzPnOdW8VtmnjPbq7S+94zGm1C2b8lYK+Qi+2NrDuBG
    /EOjf3jN4f80IpNJ+e+IyyLoG9e+dpda3m9EmshoX006c4JEQdVNo4/qWV8hAeSO
    aPWmLmjB6To6NZdB9WkpDS4Lk9TaMF+4AkVgIgtncd/U9OlP3twVAs9mXX2q+iTO
    QamPR3d5glDg9YZd3hcY8YAnVmg11uRAQE9vlA5Yqh6YXoRcSx3uU6JyhNkQPRv8
    I5Upjkig+hf95DRPfHCASTYPWbSbwfbC7Z6vCgbyHymY3vMJAgMBAAGjgYswgYgw
    CwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHQYDVR0OBBYEFHJzvAzWKIprSlEkU8z/
    E9gy8XOiMB8GA1UdIwQYMBaAFGTFHqgvIGeiybeBVVhEVr5yxmO7MA0GCSqGSIb3
    DQEBCwUAA4IBAQCYvWO2bQjR55Eeic6CfIKZyoU0+5VuhRS0bfeVApg61ChVSECR
    kACl0GjgbwWH1rcjldWEC6DVaeycwpaGwUnjGJgGMDSnQd5b7FBo0wFTaOU2E1/M
    VkZfN1XYYkmRJ24VpFB/T+ivxEl6RFYc6cNMSIC46G4S0GUOTVWcQ8hmAPOrSYNA
    MtZQK3e5zuSPHuJBnOzhk9aRyMN4ziedbEdlTgrLKmbM8TozHIoxPYtWdC/jbkiT
    jpwVwrFwDmHMTOojyLkBLFfgtRPHSr5SDlCpqAkwBhgUnuy6y/8dcxsjiG9qznk+
    LCXAikjHHP39/NPtBjz8t2k0HHpToHqNbLos
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID8TCCAtmgAwIBAgIUWfbU3yADjZ0mhUVSQC8ZmWQed3swDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjEzMTQ0MzQ2WhcNMjgxMjAz
    MTQ0MzQ2WjBzMQswCQYDVQQGEwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5l
    dyBZb3JrMQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEiMCAGA1UE
    AwwZbWlycm9yLXJlZ2lzdHJ5LnBrYXIudGVjaDCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBANQhlRpH+mUOdd8sMTrBOmSCzf5ji+fOagINq0nWx1qYl7sZ
    bpRMiKxXaASiilsCqMquifPMEDRmoF7R5DBYK2IYlZRTZoeL6LLLl7fekYFDJyqt
    tmDrsIRBEoITTR/rr//FwK7rdh1viV4mHcLPqy1LttsPjg+HIwnFb3N0JICJKdSo
    hiix/fEoReWjjyVmnfdYX/H1PcxtKkRD/KqxsZSNv3/g/Z2sEg0aKYzsluAP4d7s
    OcKduSTdaOaPFJqz+EkQNh9SOtKn8oU0lft/SZmUup1Agf0XG3oWvQQf4GLMygaN
    MAO1YgOEnW8XkZydUXn0qAuR9M5fvCs9oVgKKxECAwEAAaN9MHswCwYDVR0PBAQD
    AgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1pcnJvci1yZWdp
    c3RyeS5wa2FyLnRlY2gwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUZMUe
    qC8gZ6LJt4FVWERWvnLGY7swDQYJKoZIhvcNAQELBQADggEBAJk0V+J9BFojyKI/
    veHKb+3mCCMVfSF5XlvyrZcsIs5RXn+Y8fhwN1G6GNzw9LMFD3W7Bz1ifkBWOk/+
    KhNdy6raPX8sRIPxDygwIQCWfOm3bIlgcbHOMRx55DGmru2nKyIe+Bvlcjm+nhkL
    e3VXxeEEToxfhYIsOB9ymvb7X6Lf1Z2M7yYFqbff4Un9oYF0q7wCAVzRp1Akq1U1
    jwv6Qek6+YrLeoH9+I37V7VtOBdIkayIUnekmVx9ccl6feebZaSWYlwwiE7/Vt0C
    UIT/3L79L/uFKejFxcg49vsJ3lfWloLsPFIYlI+q3cPGUT4WAoXq76mbdwqqTEh9
    YySQXEs=
    -----END CERTIFICATE-----
