apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config
  namespace: sno-ztp
data:
  registries.conf: |
    unqualified-search-registries = ["registry.redhat.io", "registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release-images"

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp"

  policy.json: |
    {
        "default": [
            {
                "type": "insecureAcceptAnything"
            }
        ],
        "transports": {
            "docker": {
                "registry.access.redhat.com": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ],
                "registry.redhat.io": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ]
            },
            "docker-daemon": {
                "": [
                    {
                        "type": "insecureAcceptAnything"
                    }
                ]
            }
        }
    }

  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDpzCCAo+gAwIBAgIURTrOSwxBkO87FAcxEXz6AQNeICEwDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjE0MDExODM4WhcNMjcwMjA1
    MDExODM4WjAaMRgwFgYDVQQDDA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDi60N0jzkoGL3JRmJFkZKwF9MgpQZDs7buzRYp
    aBFcd3p/mQbL5Nw4tApyMd4kA2bSyrSGUBeIntHluzoFOfMz275DNw1YSovj4wh9
    Pt57EuzYgR0i8khMH4X5qkb+9Rd2tACHUfxZQJO0BBFBaDjLQlVJxLD3Xro6WSNa
    m94D1uCKdSjcBcMkCBSIPpYygEjFIWCKzv95+6QRGa8dDkYVplnUgzXGnVTi/Tvl
    g0rP+FNbsbPmBI5U7G0xz6+nSG8znJfz0dlRA9mlLoJGGMb1XS2CTtetFVY0Yxre
    +0waybtVfnGTVDHenvGUcEzGPit1gYmZrehkvGryg0E2s4o1AgMBAAGjgYswgYgw
    CwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHQYDVR0OBBYEFDLjpSOVUN6w/W0u9DW7
    AE/E3D29MB8GA1UdIwQYMBaAFPCsgLYUcVTn7RcXCXFjzFjzQsvXMA0GCSqGSIb3
    DQEBCwUAA4IBAQAV5pRiD4klQtLlEq5l1I0/RGusGaB7CYetsgCEjiUvrs5q0EJn
    fXH9DHAhmsKQbR/8u4aqUQxvbCpYoPwSEBqNacoWMwHUSVettZP06JnudJqMCEey
    QtkKj4lmZl025AF6sT2M8ralLuhmT5huSV7KIFO1E95ycGu/aquuWDxNbwMjrFlv
    YnNcRAWNXy44LvHpI4SpDNt52d+FfdT1EUHPz6LrIl64MjVLzrggI1wl0VDF3qm2
    aa/6IjugyYouFGsXwv04AICF35RS1EjxSxI723YxpaXqz+Ua6aSavRiRp5OOWqhU
    kXJrEYISI7U/eaY+CxwtvSKuq78ryXZl9qbF
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID8TCCAtmgAwIBAgIUf1Tkltk/kOSCwvrkocD7a7xwIuIwDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjE0MDExODM3WhcNMjgxMjA0
    MDExODM3WjBzMQswCQYDVQQGEwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5l
    dyBZb3JrMQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEiMCAGA1UE
    AwwZbWlycm9yLXJlZ2lzdHJ5LnBrYXIudGVjaDCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAJfFWnwmV3qsJalLJjBLChu7qCGhLg7JBLygXZaGj4tN6yqy
    n5LIpRWs5N2+AsWuLyVpbpI9+qHtXgeJGJFwJ4OoYykK3vsfTMfR8uckLihF3rbC
    vuigTtQpK2QsG11zIR1LnP4ZuDcUxpo68mREaHd8J7VkVu1T3LzSljyuYTIyIOJD
    YjsMP37q8eWHVGXd7QOxwJTAwyxJ6GRZu53HMN05Bh2XPs/0wJD3VfL8d1Vgr0dC
    9lI9SaKXqayOqj91YTJsK7XVbTaxMLQv3NHuqttIVRMHZkK+nLaun6beTxfU1sdK
    +1eYm/9Zl2oXiwOLgLPzJfreTSOO17e4IEHpZjUCAwEAAaN9MHswCwYDVR0PBAQD
    AgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1pcnJvci1yZWdp
    c3RyeS5wa2FyLnRlY2gwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU8KyA
    thRxVOftFxcJcWPMWPNCy9cwDQYJKoZIhvcNAQELBQADggEBAC9OqNvagEQkZjy1
    WEylMp1ZthKfbumMkySE+DlbGFrig5aHfzf0ktN3gCAjtXyJEdGi6zbddJDVQcgp
    3KqM3y1NLxH7B5dL9HgtU1pUmKa/C+4+0cSKwmD1H6Tmypfl7xQpmY9yqQDZziCE
    vdCIFWZ6HqIl1XBeA6Vg4h6vviknel8uYjGaAZKKKv0qBaoeoqHm+96+DlJLH44D
    wRXDuL4Mdw2wQad4u4iigvZvbcD2fWkxdkKiyDhnSgdi1dBF4+6zL0YhQj9B6peQ
    986aBO0jjk1y5XWToTS2cPUyemqV4nC4RAaCBuHyvKxlFNoSJeasu/7vxG14tf4y
    9xN+2oE=
    -----END CERTIFICATE-----
    
