apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub-common
placementBindingDefaults:
  name: hub-cluster-placement-binding

policyDefaults:
  namespace: hub-config
  placement:
    labelSelector:
      local-cluster: "true"
  remediationAction: enforce
  severity: high
  namespaceSelector:
    exclude:
      - kube-*
    include:
      - '*'
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s

policies:

# Wave 10 - Common/base configurations
- name: hub-cluster-authentication
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    policy.open-cluster-management.io/description: Authentication and authorization resources for htpass
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-03 Access Enforcement
  manifests:
    # Authentication
    - path: ../hub/auth/group.yaml
    - path: ../hub/auth/crb.yaml
    - path: ../hub/auth/oauth.yaml
    - path: ../hub/auth/secrets.yaml    

- name: hub-cluster-banner
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    policy.open-cluster-management.io/description: HUB Cluster Banner
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-02 Baseline Configuration  
  manifests:
    - path: ../hub/console/console-banner.yaml    

- name: hub-cluster-tools
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    policy.open-cluster-management.io/description: Installs and configures the NFS Storage and RHACM 
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-02 Baseline Configuration
  manifests:
    # NFS Storage 
    - path: ../hub/nfs/00-ns-kubenfs.yaml
    - path: ../hub/nfs/01-nfs-rbac.yaml
    - path: ../hub/nfs/02-nfs-deployment.yaml
    - path: ../hub/nfs/03-storage-class.yaml

    # RHACM operator
    #   Note: RHACM is part of the hub cluster seeding process.  These CRs are there for Day 2 configration only.
    - path: ../hub/acm/00-ns-acm.yaml
    - path: ../hub/acm/01-og-acm.yaml
    - path: ../hub/acm/02-sub-acm.yaml

# Wave 20 - multiclusterhub configuration
- name: hub-cluster-ztp-config
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "20"
    policy.open-cluster-management.io/description: Configure Multi Cluster Hub
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-02 Baseline Configuration    
  manifests:
    - path: ../hub/acm/03-mch-acm.yaml  

- name: hub-cluster-assisted-installer
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "20"
    policy.open-cluster-management.io/description: Assisted Instller templates for SNO clusters
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-02 Baseline Configuration
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: "true"    
  manifests:
    - path: ../hub/custom-template/ai-namespace-custom-templates.yaml
    - path: ../hub/custom-template/ai-custom-cluster-templates-v1.yaml
    - path: ../hub/custom-template/ai-custom-node-templates-v1.yaml    

- name: hub-cluster-agent-service
  policyAnnotations:
    ran.openshift.io/ztp-deploy-wave: "20"
    policy.open-cluster-management.io/description: AgentServiceConfig for rootFS and ISO images, with status check
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-02 Baseline Configuration
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: "true"    
  manifests:
    - path: ../hub/agent/00-provisioning.yaml  
    - path: ../hub/agent/01-agent-service-config.yaml
    - path: ../hub/agent/agentserviceconfig-status.yaml
