apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: vmware-storage-map
  namespace: konveyor-forklift
spec:
  map:
    - destination:
        storageClass: hostpath-csi
        accessMode: ReadWriteOnce
      source:
        name: datastore1
  provider:
    destination:
      name: host
      namespace: konveyor-forklift
    source:
      name: vsphere-provider
      namespace: konveyor-forklift
---
apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: vmware-network-map
  namespace: konveyor-forklift
spec:
  map:
    - destination:
        name: bridge-whereabouts
        namespace: virtualmachines
        type: multus
        #type: pod
      source:
        name: pk-lan
  provider:
    destination:
      name: host
      namespace: konveyor-forklift
    source:
      name: vsphere-provider
      namespace: konveyor-forklift
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  name: win-vm-mig-plan
  namespace: konveyor-forklift
spec:
  preserveStaticIPs: true
  archived: false
  description: ''
  map:
    network:
      name: vmware-network-map
      namespace: konveyor-forklift
    storage:
      name: vmware-storage-map
      namespace: konveyor-forklift
  provider:
    destination:
      name: host
      namespace: konveyor-forklift
    source:
      name: vsphere-provider
      namespace: konveyor-forklift
  targetNamespace: virtualmachines
  vms:
    - hooks: []
      name: win10
  warm: false
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Migration
metadata:
  name: win-migration
  namespace: konveyor-forklift
spec:
  plan:
    name: win-vm-mig-plan
    namespace: konveyor-forklift
