apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: golden-img-vm
  namespace: kubevirt-images
  labels:
    kubevirt.io/os: linux
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
            - name: configmap-volume
              disk:
                bus: virtio
            - name: script-secret-disk
              disk:
              serial: D23YZ9W6WA5DJ487
            - name: cloudinitdisk
              cdrom:
                bus: sata
                readonly: true
          interfaces:
            - name: default
              masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      networks:
        - name: default
          pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: rhel9-golden-image
      - name: configmap-volume
        configMap:
          name: start-up      
      - name: script-secret-disk
        secret:
          secretName: secret-for-scripts
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: golden-image-vm
            ssh_pwauth: True
            disable_root: false
            users:
            - name: m104461
              ssh_pwauth: True
              gecos: ME I
              lock_passwd: false
              sudo: ALL=(ALL) NOPASSWD:ALL
              passwd: $6$973aNqfpSqo0NTvb$E.sN1X9j8X29ouYLXsTeyJnT/Hk4encLCQfI9cECqgzUQoAKF.aYSDiD/zhZGbfZXrGLk6UuAOhJIkHjBmuAw/
            bootcmd:
              # mount configmap disks           
              - "sudo mkdir /mnt/secret-for-scripts"
              - "sudo mount /dev/$(lsblk --nodeps -no name,serial | grep D23YZ9W6WA5DJ487 | cut -f1 -d' ') /mnt/secret-for-scripts"
              # mount configmap disks
              - mkdir -p /mnt/myconfigmap
              - mount /dev/vdb /mnt/myconfigmap
              #make it executable
              - cp -r /mnt/myconfigmap /tmp 
              - chmod -R +x /tmp/myconfigmap
            runcmd:
              #run scripts automatically
              - "sh /tmp/myconfigmap/01-set-dns.sh"   
              - "sh /tmp/myconfigmap/02-set-chrony.sh" 
              - "sh /tmp/myconfigmap/03-set-subscription-manager.sh"              
              - "sh /tmp/myconfigmap/04-patch-rhel9.sh"
              - "sh /tmp/myconfigmap/05-tools-downloader-installer.sh" 
              - "sh /tmp/myconfigmap/06-set-firewall.sh"           
              - "sh /tmp/myconfigmap/08-off-subscription-manager.sh" 
              #- "sh /tmp/myconfigmap/09-logbase-line.sh"    
              - "sh /tmp/myconfigmap/10-log_rotate.sh" 
              - "sh /tmp/myconfigmap/11-system-cleanup.sh"
                
