kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admin
users:
  - afilice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-htpasswd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cluster-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'kube:admin'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:admin'
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cluster-admin    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: htpasswd-secret
spec:
  externalSecretName: htpasswd-secret
  externalSecretSpec:
    dataFrom:
      - extract:
          conversionStrategy: Default
          decodingStrategy: None
          key: secret/data/htpasswd
          metadataPolicy: None
        rewrite:
          - regexp:
              source: htpasswd
              target: htpasswd
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: htpass-secret
  namespaces:
    - openshift-config
  refreshTime: 1m
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: HTPasswd
      type: HTPasswd
