apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      domain:
        cpu:
          cores: 1
          model: Haswell-noTSX-IBRS
        resources:
          requests:
            memory: 4G
        devices:
          disks:
            - name: fedora-vm-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: podnet
            masquerade: {}    
      networks:
        - name: podnet
          pod: {}
      volumes:
        - name: fedora-vm-pvc
          persistentVolumeClaim:
            claimName: fedora-vm-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 2
                renderer: networkd
                ethernets:
                  enp1s0:
                    dhcp4: true
            userData: |-
              #cloud-config
              hostname: fedora-vm
              user: root
              password: passwd
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: false
              ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD6XPuoZ4Zr18Mwdy2rYYTSU0fnNva8B1zW4b9Qfk6wiR703eLC3Tv0uuSQe4aBlVwaHzrzbv3DRg5mZev2TAKvNvr/o25lJgUWUjDEmYcpJO+UbbVfDt7HJSstmQJCraLb48jeBsyVzouinJCRncXxdU6UdT4SXVmsKYomCV54pugn/OfDccKtSRL22KSZRIht0XAbk2FmEzQ7aqq+O9eaixbrT7UVXdfhViWBTELsHP7Gx4ZMFqjGoXv0oY9CsMOSWlyDz05fJhncARkjSMtisyxis+GcKFo9nl/GeLQOZ8kB+8ZtK9eKBmenS+gurcNq4nAGOSHyZ5483UmyYypL cloudcafe
              runcmd:
                - "sudo touch /root/installed /tmp/foo"
                - "sudo dnf update"
                - "sudo dnf install httpd fastfetch -y"
                - "sudo systemctl daemon-reload"
                - "sudo systemctl enable httpd"
                - "sudo systemctl start --no-block httpd"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io/vm: fedora-vm
  name: fedora-vm
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: httpd
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/vm: fedora-vm
  type: LoadBalancer
