apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "debian-12-image"
  namespace: virtualmachines
spec:
  source:
      http:
        url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.raw"
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "30G"
    storageClassName: kubenfs-storage
