apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policies-hub-cluster
placementBindingDefaults:
  # Set an explicit placement binding name to use rather than rely on the default.
  name: "placementbinding"

policyDefaults:
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"
  namespaceSelector:
    include: ["*"]
    exclude: []
  namespace: open-cluster-management-policies
  remediationAction: inform
  complianceType: "musthave"
  severity: low
  pruneObjectBehavior: "None"
  metadataComplianceType: "musthave"

policySets:
  - name: hub
    description: "Hub cluster"
    placement:
      name: "hub-placement"
      labelSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - local-cluster

    policies:
      - disable-operator
      - oauth-configuration
      - install-cert-manager

policies:
  - name: disable-operator
    description: "Disable community-operators redhat-marketplace and certified-operators"
    manifests:
      - path: ../policies/global/common/disable-operator.yaml
    remediationAction: enforce
    categories:
      - "CM Configuration Management"
    controls:
      - "CM-2 Baseline Configuration"
    standards:
      - "NIST SP 800-53"
    severity: low

  - name: oauth-configuration
    description: "Configure HTTPaswd authentication and associated roles"
    manifests:
      - path: ../policies/global/security-auth/htpasswd.yaml
    remediationAction: enforce
    categories:
      - "SC System and Communications Protection"
    controls:
      - "SC-1 SYSTEM AND COMMUNICATIONS PROTECTION POLICY AND PROCEDURES"
    standards:
      - "NIST SP 800-53"
    severity: high

  - name: install-cert-manager
    description: "Install and configure Cert Manager for certificate management"
    manifests:
      - path: ../policies/global/operators/certmanager-operator.yaml
    remediationAction: enforce
    categories:
      - "CM Configuration Management"
    controls:
      - "CM-2 Baseline Configuration"
    standards:
      - "NIST SP 800-53"
    severity: low
