apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-disable-operator
  namespace: sno2-ztp
data:
  disable-operator.yaml: |
    apiVersion: config.openshift.io/v1
    kind: OperatorHub
    metadata:
      name: cluster
    spec:
      sources:
      - disabled: true
        name: redhat-operators
      - disabled: true
        name: community-operators
      - disabled: true
        name: certified-operators
      - disabled: true
        name: redhat-marketplace
