apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-custom-node-templates-v1
  namespace: open-cluster-management
data:
  BareMetalHost: "apiVersion: metal3.io/v1alpha1\nkind: BareMetalHost\nmetadata:\n{{
    if .SpecialVars.CurrentNode.HostRef }}\n  name: \"{{ .SpecialVars.CurrentNode.HostRef.Name
    }}\"\n  namespace: \"{{ .SpecialVars.CurrentNode.HostRef.Namespace }}\"\n{{ else
    }}\n  name: \"{{ .SpecialVars.CurrentNode.HostName }}\"\n  namespace: \"{{ .Spec.ClusterName
    }}\" \n{{ end }}    \n  annotations:\n    siteconfig.open-cluster-management.io/sync-wave:
    \"3\"\n    inspect.metal3.io: \"{{ .SpecialVars.CurrentNode.IronicInspect }}\"\n{{
    if .SpecialVars.CurrentNode.NodeLabels }}\n{{ range $key, $value := .SpecialVars.CurrentNode.NodeLabels
    }}\n    bmac.agent-install.openshift.io.node-label.{{ $key }}: {{ $value | quote}}\n{{
    end }}\n{{ end }}\n    bmac.agent-install.openshift.io/hostname: \"{{ .SpecialVars.CurrentNode.HostName
    }}\"\n{{ if .SpecialVars.CurrentNode.InstallerArgs  }}\n    bmac.agent-install.openshift.io/installer-args:
    '{{ .SpecialVars.CurrentNode.InstallerArgs  }}'\n{{ end }}\n{{ if .SpecialVars.CurrentNode.IgnitionConfigOverride
    }}\n    bmac.agent-install.openshift.io/ignition-config-overrides: '{{ .SpecialVars.CurrentNode.IgnitionConfigOverride
    }}'\n{{ end }}\n    bmac.agent-install.openshift.io/role: \"{{ .SpecialVars.CurrentNode.Role
    }}\"\n  labels:\n{{ if .SpecialVars.CurrentNode.HostRef }}\n    infraenvs.agent-install.openshift.io:
    \"{{ .SpecialVars.CurrentNode.HostRef.Name }}\"\n{{ else }}\n    infraenvs.agent-install.openshift.io:
    \"{{ .SpecialVars.CurrentNode.HostName }}\"\n{{ end }}\n    cluster.open-cluster-management.io/backup:
    cluster-activation\nspec:\n  bootMode: \"{{ .SpecialVars.CurrentNode.BootMode
    }}\"\n  bmc:\n    address: \"{{ .SpecialVars.CurrentNode.BmcAddress }}\"\n    disableCertificateVerification:
    true\n    credentialsName: \"{{ .SpecialVars.CurrentNode.BmcCredentialsName.Name
    }}\"\n  bootMACAddress: \"{{ .SpecialVars.CurrentNode.BootMACAddress }}\"\n  automatedCleaningMode:
    \"{{ .SpecialVars.CurrentNode.AutomatedCleaningMode }}\"\n  online: true\n{{ if
    .SpecialVars.CurrentNode.CPUArchitecture }}\n  architecture: \"{{ .SpecialVars.CurrentNode.CPUArchitecture
    }}\"\n{{ else if and\n    (.Spec.CPUArchitecture)\n    (ne .Spec.CPUArchitecture
    \"multi\")\n}}\n  architecture: \"{{ .Spec.CPUArchitecture }}\"\n{{ end }}\n{{
    if .SpecialVars.CurrentNode.RootDeviceHints }}\n  rootDeviceHints:\n{{ .SpecialVars.CurrentNode.RootDeviceHints
    | toYaml | indent 4 }}\n{{ end }}"
  InfraEnv: |-
    apiVersion: agent-install.openshift.io/v1beta1
    kind: InfraEnv
    metadata:
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "1"
      name: "{{ .Spec.ClusterName }}"
      namespace: "{{ .Spec.ClusterName }}"
      labels:
        baremetalhost.metal3.io/namespace: "{{ .Spec.ClusterName }}"
    spec:
      kernelArguments:
       - operation: append
         value: 'coreos.live.rootfs_url=http://192.168.0.159:8080/ocp/rhcos-4.20.11-x86_64-live-rootfs.x86_64.img'
      clusterRef:
        name: "{{ .Spec.ClusterName }}"
        namespace: "{{ .Spec.ClusterName }}"
      sshAuthorizedKey: "{{ .Spec.SSHPublicKey }}"
    {{ if .Spec.Proxy }}
      proxy:
    {{ .Spec.Proxy | toYaml | indent 4 }}
    {{ end }}
      pullSecretRef:
        name: "{{ .Spec.PullSecretRef.Name }}"
      ignitionConfigOverride: '{{ .Spec.IgnitionConfigOverride }}'
      mirrorRegistryRef:
        name: mirror-registry-config
        namespace: "{{ .Spec.ClusterName }}"
      nmStateConfigLabelSelector:
        matchLabels:
          nmstate-label: "{{ .Spec.ClusterName }}"
    {{ if .Spec.AdditionalNTPSources }}
      additionalNTPSources:
    {{ .Spec.AdditionalNTPSources | toYaml | indent 4 }}
    {{ end }}
  NMStateConfig: |-
    {{ if .SpecialVars.CurrentNode.NodeNetwork }}
    apiVersion: agent-install.openshift.io/v1beta1
    kind: NMStateConfig
    metadata:
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "1"
    {{ if .SpecialVars.CurrentNode.HostRef }}
      name: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
      namespace: "{{ .SpecialVars.CurrentNode.HostRef.Namespace }}"
    {{ else }}
      name: "{{ .SpecialVars.CurrentNode.HostName }}"
      namespace: "{{ .Spec.ClusterName }}"
    {{ end }}
      labels:
    {{ if .SpecialVars.CurrentNode.HostRef }}
        nmstate-label: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
    {{ else }}
        nmstate-label: "{{ .SpecialVars.CurrentNode.HostName }}"
    {{ end }}
    spec:
      config:
    {{ .SpecialVars.CurrentNode.NodeNetwork.NetConfig | toYaml | indent 4}}
      interfaces:
    {{ .SpecialVars.CurrentNode.NodeNetwork.Interfaces | toYaml | indent 4 }}
    {{ end }}
immutable: true
