apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-custom-node-templates-v1
  namespace: open-cluster-management
data:
  BareMetalHost: |-
    apiVersion: metal3.io/v1alpha1
    kind: BareMetalHost
    metadata:
    {{ if .SpecialVars.CurrentNode.HostRef }}
      name: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
      namespace: "{{ .SpecialVars.CurrentNode.HostRef.Namespace }}"
    {{ else }}
      name: "{{ .SpecialVars.CurrentNode.HostName }}"
      namespace: "{{ .Spec.ClusterName }}"
    {{ end }}
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "3"
        inspect.metal3.io: "{{ .SpecialVars.CurrentNode.IronicInspect }}"
    {{ if .SpecialVars.CurrentNode.NodeLabels }}

    {{ range $key, $value := .SpecialVars.CurrentNode.NodeLabels }}
        bmac.agent-install.openshift.io.node-label.{{ $key }}: {{ $value | quote}}
    {{ end }}

    {{ end }}
        bmac.agent-install.openshift.io/hostname: "{{ .SpecialVars.CurrentNode.HostName }}"
    {{ if .SpecialVars.CurrentNode.InstallerArgs  }}
        bmac.agent-install.openshift.io/installer-args: '{{ .SpecialVars.CurrentNode.InstallerArgs  }}'
    {{ end }}

    {{ if .SpecialVars.CurrentNode.IgnitionConfigOverride }}
        bmac.agent-install.openshift.io/ignition-config-overrides: '{{ .SpecialVars.CurrentNode.IgnitionConfigOverride }}'
    {{ end }}
        bmac.agent-install.openshift.io/role: "{{ .SpecialVars.CurrentNode.Role }}"
      labels:
    {{ if .SpecialVars.CurrentNode.HostRef }}
        infraenvs.agent-install.openshift.io: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
    {{ else }}
        infraenvs.agent-install.openshift.io: "{{ .SpecialVars.CurrentNode.HostName }}"
    {{ end }}
        cluster.open-cluster-management.io/backup: cluster-activation
    spec:
      bootMode: "{{ .SpecialVars.CurrentNode.BootMode }}"
      bmc:
        address: "{{ .SpecialVars.CurrentNode.BmcAddress }}"
        disableCertificateVerification: true
        credentialsName: "{{ .SpecialVars.CurrentNode.BmcCredentialsName.Name }}"
      bootMACAddress: "{{ .SpecialVars.CurrentNode.BootMACAddress }}"
      automatedCleaningMode: "{{ .SpecialVars.CurrentNode.AutomatedCleaningMode }}"
      online: true
    {{ if .SpecialVars.CurrentNode.CPUArchitecture }}
      architecture: "{{ .SpecialVars.CurrentNode.CPUArchitecture }}"
    {{ else if and
        (.Spec.CPUArchitecture)
        (ne .Spec.CPUArchitecture "multi")
    }}
      architecture: "{{ .Spec.CPUArchitecture }}"
    {{ end }}

    {{ if .SpecialVars.CurrentNode.RootDeviceHints }}
      rootDeviceHints:
    {{ .SpecialVars.CurrentNode.RootDeviceHints | toYaml | indent 4 }}

    {{ end }}

  InfraEnv: |-
    apiVersion: agent-install.openshift.io/v1beta1
    kind: InfraEnv
    metadata:
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "1"
      name: "{{ .Spec.ClusterName }}"
      namespace: "{{ .Spec.ClusterName }}"
      labels:
        baremetalhost.metal3.io/namespace: "{{ .Spec.ClusterName }}"
    spec:
      kernelArguments:
       - operation: append
         value: 'coreos.live.rootfs_url=http://{{ .Spec.ClusterName }}-mr.pkar.tech:8080/ocp/rhcos-4.18.30-x86_64-live-rootfs.x86_64.img'
      clusterRef:
        name: "{{ .Spec.ClusterName }}"
        namespace: "{{ .Spec.ClusterName }}"
      sshAuthorizedKey: "{{ .Spec.SSHPublicKey }}"
    {{ if .Spec.Proxy }}
      proxy:
    {{ .Spec.Proxy | toYaml | indent 4 }}
    {{ end }}
      pullSecretRef:
        name: "{{ .Spec.PullSecretRef.Name }}"
      ignitionConfigOverride: '{{ .Spec.IgnitionConfigOverride }}'
      mirrorRegistryRef:
        name: mirror-registry-config
        namespace: "{{ .Spec.ClusterName }}"
      nmStateConfigLabelSelector:
        matchLabels:
          nmstate-label: "{{ .Spec.ClusterName }}"
    {{ if .Spec.AdditionalNTPSources }}
      additionalNTPSources:
    {{ .Spec.AdditionalNTPSources | toYaml | indent 4 }}
    {{ end }}
  NMStateConfig: |-
    {{ if .SpecialVars.CurrentNode.NodeNetwork }}
    apiVersion: agent-install.openshift.io/v1beta1
    kind: NMStateConfig
    metadata:
      annotations:
        siteconfig.open-cluster-management.io/sync-wave: "1"
    {{ if .SpecialVars.CurrentNode.HostRef }}
      name: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
      namespace: "{{ .SpecialVars.CurrentNode.HostRef.Namespace }}"
    {{ else }}
      name: "{{ .SpecialVars.CurrentNode.HostName }}"
      namespace: "{{ .Spec.ClusterName }}"
    {{ end }}
      labels:
    {{ if .SpecialVars.CurrentNode.HostRef }}
        nmstate-label: "{{ .SpecialVars.CurrentNode.HostRef.Name }}"
    {{ else }}
        nmstate-label: "{{ .SpecialVars.CurrentNode.HostName }}"
    {{ end }}
    spec:
      config:
    {{ .SpecialVars.CurrentNode.NodeNetwork.NetConfig | toYaml | indent 4}}
      interfaces:
    {{ .SpecialVars.CurrentNode.NodeNetwork.Interfaces | toYaml | indent 4 }}
    {{ end }}
immutable: true
