apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocp-ztp-gitops
  namespace: ocp-ztp-gitops-policies
spec:
  clusterSet: ocp-ztp-gitops
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocp-ztp-gitops
  namespace: hcp-ztp
spec:
  clusterSet: ocp-ztp-gitops
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocp-ztp-gitops
  namespace: sno-ztp
spec:
  clusterSet: ocp-ztp-gitops
