apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: common
placementBindingDefaults:
  name: placementbinding
policyDefaults:
  namespace: open-cluster-management-policies
  remediationAction: enforce
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 10s
policySets:
  - name: sno-ztp
    placement:
      name: sno-placement
      labelSelector:
        matchExpressions:
          - key: cluster-name
            operator: NotIn
            values:
              - sno-ztp
    policies:
      - metallb-operator
policies:
  - name: metallb-operator
    manifests:
      - path: input/policy-manifests/metallb-operator.yaml
  - name: compliance-operator
    manifests:
      - path: input/policy-manifests/compliance-operator.yaml
